export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_SELECTED_COURSE_SUCCESS = 'LOAD_SELECTED_COURSE_SUCCESS';
export const LIKE_SELECTED_COURSE_SUCCESS = 'LIKE_SELECTED_COURSE_SUCCESS';
export const ENROLL_SELECTED_COURSE_SUCCESS = 'ENROLL_SELECTED_COURSE_SUCCESS';
// export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
// export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
// export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
